### PR TITLE
Add option to open the buffer in split(horizontal/vertical)

### PR DESCRIPTION
**Pull request by linnovs**
#28

### CODE REVIEW

**Comment by leath-dub** [comment]
I will keep this open for now, I have actually started rewriting the plugin. This kind of functionality will be able to very cleanly be separated from the menu itself.

**Comment by leath-dub** [comment]
Based on this commit I adjusted it for `snipe2`, I cant figure out how to add you as a contributor manually though :(.

**Comment by linnovs** [comment]
I'll gladly test the `snipe2` branch and provide my feedback.

**Comment by linnovs** [comment]
After testing, `snipe2` branch works as expected. I believe this PR can be closed. Let me know if there's anything else I can assist with.

**Pull request closed without merging**
